# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: debug-whoami
        run: curl https://ifconfig.me

      - name: debug-git-host
        run: host git.code.sf.net

      - name: debug-main-host
        run: host sourceforge.net
        
      - name: debug-git-ping
        run: ping sourceforge.net -c 4

      - name: debug-main-ping
        run: ping git.code.sf.net -c 4

      - name: debug-main-curl
        run: curl https://sourceforge.net
        
      - name: debug-git-curl
        run: curl https://git.code.sf.net

        
      - name: debug-git-mtr
        run: |
          apt-get update -y
          apt-get install -y mtr
          mtr -4wb git.code.sf.net
          
      - name: get liblibspectrum
        run: |
          mkdir -p libspectrum
          cd libspectrum
      
      - name: get code
        run: |
          git config --global user.email "etfeet@gmail.com"
          git config --global user.name "etfeet"
          git clone git://git.code.sf.net/p/fuse-emulator/libspectrum
        
